name: Expo CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Check Expo Project
        run: npx expo-doctor

      - name: Export Project
        run: npx expo export

      - name: Upload Build Output
        uses: actions/upload-artifact@v4
        with:
          name: expo-export
          path: dist